### PR TITLE
Libraryupdates

### PR DESCRIPTION
**Pull request by SnehaGunda**

### CODE REVIEW

**Comment by SnehaGunda** [comment]
@burkeholland Change in this PR corresponds to git issue: https://github.com/MicrosoftDocs/azure-docs/issues/10541 Please review and merge, there might be other updates I see the views folder contains jade files. 

Can you please update this doc too: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-application

**Comment by burkeholland** [comment]
Even though Jade has been renamed to Pug, the Express generator still outputs Jade files. That means that the docs should stay the same or we would have to advise people to change over to Pug. That seems like an unnecessary step to me as Jade works just fine.

**Comment by SnehaGunda** [comment]
@burkeholland I think it makes sense for docs and code to be consistent in the step5 https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-application#_Toc395783181 . If pug updates are merged, docs should be updated to use pug or revert the changes I made to use Jade. 

can you help with doc updates? or revert back the changes?

**Comment by burkeholland** [comment]
I can revert it back. I think it's such a small thing and it doesn't add
any value to the project, but at least 3 more steps to the docs.

**Pull request merged**
